import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import Link from 'next/link'
import { getFoodBanks, getFoodBank } from '../../server/database';

export default function FoodBank({ oneFoodBank }) {

    const foodBankComponent = oneFoodBank[0]

    return (
        <div className={styles.container}>
            <Head>
                <title>LocalToMe</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>LocalToMe</h1>

            <h2>{foodBankComponent.programName}</h2>

            <main className={styles.main}>
            </main>

            <footer className={styles.footer}>
            </footer>
        </div>
    )
}

export async function getServerSideProps({ params }) {
    const req = await getFoodBank(params);
    const oneFoodBank = JSON.parse(JSON.stringify(req));
    console.log(oneFoodBank)
    return {
        props: { oneFoodBank },
    }
}