import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import Link from 'next/link'
import { getFoodBanks } from '../../server/database';

export default function Home({ foodBanksList }) {

    const foodBankComponent = foodBanksList.map((fb) => (
        <li key={fb.id}>
            <p>{fb.programName}</p>
        </li>
    ))

    return (
        <div className={styles.container}>
            <Head>
                <title>LocalToMe</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>LocalToMe</h1>

            <ul>{foodBankComponent}</ul>
            <main className={styles.main}>
            </main>

            <footer className={styles.footer}>
            </footer>
        </div>
    )
}

export async function getServerSideProps(context) {
    // Everything in this function happens on the server
    const foodBanksData = await getFoodBanks();
    const foodBanksList = JSON.parse(JSON.stringify(foodBanksData));
    console.log(foodBanksList)
    return {
        props: { foodBanksList } // will be passed to the page component as props
    }
}