import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import Link from 'next/link'
import { getFoodBanks, getFoodBank, addFoodBank } from '../../server/database';

export default function FoodBank({ data }) {

    // boolean no shopping up yet oops

    return (
        <div className={styles.container}>
            <Head>
                <title>LocalToMe</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>{data.programName}</h1>
                <h2>organizationName:{data.organizationName}</h2>
                <h3>populationServed:{data.populationServed}</h3>
                <p>wheelchairAcessible:{data.wheelchairAcessible}</p>
                <h3>signupRequired:{data.signupRequired}</h3>
                <p>requiresReferral:{data.requiresReferral}</p>
                <p>signupEmail:{data.signupEmail}</p>
                <h3>locationAddress:{data.locationAddress}</h3>
                <p>localAreas:{data.localAreas}</p>
                <p>deliveryAvailable:{data.deliveryAvailable}</p>
                <p>takeoutAvailable:{data.takeoutAvailable}</p>
                <p>hamperCost: {data.hamperCost}</p>
                <p>providesHampers:{data.providesHampers}</p>
                <p>providesMeals:{data.providesMeals}</p>
                <h3>Description:</h3>
                <p>{data.description}</p>
                <p>lastUpdatedDate:{data.lastUpdatedDate}</p>

            </main>

            <footer className={styles.footer}>
            </footer>
        </div>
    )
}

export async function getServerSideProps({ params }) {
    // console.log(params.id)
    const req = await getFoodBank(params.id)
    const data = JSON.parse(JSON.stringify(req));
    // console.log(data)

    // set all foodbank data in firestore
    // const fbDataAPI = await fetch("https://opendata.vancouver.ca/api/records/1.0/search/?dataset=free-and-low-cost-food-programs&q=&rows=200&facet=program_name&facet=local_areas&facet=provides_meals&facet=provides_hampers&facet=takeout_available&facet=wheelchair_accessible&facet=signup_required&facet=requires_referral");
    // console.log(`this one: ${fbDataAPI}`);
    // const fbDataToJson = await fbDataAPI.json()
    // console.log(fbDataToJson.records);
    // let formattedFbData = fbDataToJson.records.map((fb) => fb.fields)
    // formattedFbData.map(async (fb) => {
    //     await addFoodBank(fb)
    // })

    return {
        props: { data },
    }
}

// export async function getServerSideProps(context) {
//     const data = await fetch("https://opendata.vancouver.ca/api/records/1.0/search/?dataset=free-and-low-cost-food-programs&q=&rows=200&facet=program_name&facet=local_areas&facet=provides_meals&facet=provides_hampers&facet=takeout_available&facet=wheelchair_accessible&facet=signup_required&facet=requires_referral");
//     console.log(data);
//     // const runAddFoodBanks = await addFoodBank(foodBanks);

// }