import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import Link from 'next/link'
import { getFoodBank } from '../../server/database';

export default function FoodBank({ data }) {

    // boolean no shopping up yet oops
    const singleFBComponent = data.map((d) => {
        // console.log(data)
        return (
            <>
                < h1 > {d.program_name.stringValue}</ h1 >
                {d.organization_name.stringValue && (<h2>Organization Name: {d.organization_name.stringValue}</h2>)}
                {d.program_population_served && (<h3>Population Served: {d.program_population_served.stringValue}</h3>)}
                {d.wheelchair_accessible && (<p>Wheelchair Acessible: {d.wheelchair_accessible.stringValue}</p>)}
                {d.signup_required && (<h3>Signup Required: {d.signup_required.stringValue}</h3>)}
                {d.requires_referral && (<p>requiresReferral: {d.requires_referral.stringValue}</p>)}
                {d.signup_email && (<p>signupEmail: {d.signup_email.stringValue}</p>)}
                {d.location_address && (<h3>locationAddress: {d.location_address.stringValue}</h3>)}
                {d.local_areas && (<p>localAreas: {d.local_areas.stringValue}</p>)}
                {d.delivery_available && (<p>deliveryAvailable: {d.delivery_available.stringValue}</p>)}
                {d.takeout_available && (<p>takeoutAvailable: {d.takeout_available.stringValue}</p>)}
                {d.hamper_cost && (<p>hamperCost: {d.hamper_cost.stringValue}</p>)}
                {d.provides_hampers && (<p>providesHampers: {d.provides_hampers.stringValue}</p>)}
                {d.provides_meals && (<p>providesMeals: {d.provides_meals.stringValue}</p>)}
                {d.description && (<><h3>Description:</h3><p>{d.description.stringValue}</p></>)}
                {d.last_updated_date && (<p>lastUpdatedDate: {d.last_updated_date.stringValue}</p>)}
            </>
        )
    })

    return (
        <div className={styles.container}>
            <Head>
                <title>LocalToMe</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {singleFBComponent}
                {/* <h1>{data.program_name}</h1>
                <h2>organizationName:{data.organizationName}</h2>
                <h3>populationServed:{data.populationServed}</h3>
                <p>wheelchairAcessible:{data.wheelchairAcessible}</p>
                <h3>signupRequired:{data.signupRequired}</h3>
                <p>requiresReferral:{data.requiresReferral}</p>
                <p>signupEmail:{data.signupEmail}</p>
                <h3>locationAddress:{data.locationAddress}</h3>
                <p>localAreas:{data.localAreas}</p>
                <p>deliveryAvailable:{data.deliveryAvailable}</p>
                <p>takeoutAvailable:{data.takeoutAvailable}</p>
                <p>hamperCost: {data.hamperCost}</p>
                <p>providesHampers:{data.providesHampers}</p>
                <p>providesMeals:{data.providesMeals}</p>
                <h3>Description:</h3>
                <p>{data.description}</p>
                <p>lastUpdatedDate:{data.lastUpdatedDate}</p> */}

            </main>

            <footer className={styles.footer}>
            </footer>
        </div>
    )
}

export async function getServerSideProps({ params }) {
    // console.log(params.id)
    const req = await getFoodBank(params.id)
    // console.log(req)
    const oneFoodBankObj = JSON.parse(JSON.stringify(req));
    const data = [oneFoodBankObj._document.data.value.mapValue.fields]
    // console.log(data)

    // set all foodbank data in firestore
    // const fbDataAPI = await fetch("https://opendata.vancouver.ca/api/records/1.0/search/?dataset=free-and-low-cost-food-programs&q=&rows=200&facet=program_name&facet=local_areas&facet=provides_meals&facet=provides_hampers&facet=takeout_available&facet=wheelchair_accessible&facet=signup_required&facet=requires_referral");
    // console.log(`this one: ${fbDataAPI}`);
    // const fbDataToJson = await fbDataAPI.json()
    // console.log(fbDataToJson.records);
    // let formattedFbData = fbDataToJson.records.map((fb) => fb.fields)
    // formattedFbData.map(async (fb) => {
    //     await addFoodBank(fb)
    // })

    return {
        props: { data },
    }
}

// export async function getServerSideProps(context) {
//     const data = await fetch("https://opendata.vancouver.ca/api/records/1.0/search/?dataset=free-and-low-cost-food-programs&q=&rows=200&facet=program_name&facet=local_areas&facet=provides_meals&facet=provides_hampers&facet=takeout_available&facet=wheelchair_accessible&facet=signup_required&facet=requires_referral");
//     console.log(data);
//     // const runAddFoodBanks = await addFoodBank(foodBanks);

// }