import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import Link from 'next/link'
import { getFoodBanks, getFoodBank } from '../../server/database';

export default function FoodBank({ data }) {

    // boolean no shopping up yet oops

    return (
        <div className={styles.container}>
            <Head>
                <title>LocalToMe</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>{data.programName}</h1>
                <h2>organizationName:{data.organizationName}</h2>
                <h3>populationServed:{data.populationServed}</h3>
                <p>wheelchairAcessible:{data.wheelchairAcessible}</p>
                <h3>signupRequired:{data.signupRequired}</h3>
                <p>requiresReferral:{data.requiresReferral}</p>
                <p>signupEmail:{data.signupEmail}</p>
                <h3>locationAddress:{data.locationAddress}</h3>
                <p>localAreas:{data.localAreas}</p>
                <p>deliveryAvailable:{data.deliveryAvailable}</p>
                <p>takeoutAvailable:{data.takeoutAvailable}</p>
                <p>hamperCost: {data.hamperCost}</p>
                <p>providesHampers:{data.providesHampers}</p>
                <p>providesMeals:{data.providesMeals}</p>
                <h3>Description:</h3>
                <p>{data.description}</p>
                <p>lastUpdatedDate:{data.lastUpdatedDate.seconds}</p>

            </main>

            <footer className={styles.footer}>
            </footer>
        </div>
    )
}

export async function getServerSideProps({ params }) {
    // console.log(params.id)
    const req = await getFoodBank(params.id)
    const data = JSON.parse(JSON.stringify(req));
    console.log(data)

    return {
        props: { data },
    }
}